config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#top"

  get 'home/about'

  resources :recipes, only: [:create, :index, :show, :update, :edit, :destroy]
  resources :users, only: [:show, :edit, :index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_recipe, only: [:edit]

  def create
    @recipes = Recipe.all
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:complete] = "Recipe was successfully created"
      redirect_to recipe_path(@recipe)
    else
      @user = current_user
      render "index"
    end
  end

  def index
    @recipes = Recipe.all
    @recipe = Recipe.new
    @user = current_user
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipes = Recipe.all
    @recipe_new = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:complete] = "Recipe was successfully updated"
      redirect_to recipe_path(@recipe)
    else
      render "edit"
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body, :user_id)
  end

  def correct_recipe
    recipe = Recipe.find(params[:id])
    if recipe.user != current_user
      redirect_to recipes_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_signed_in?

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
    @recipe = Recipe.new
  end

  def index
    @users = User.all
    @user = current_user
    @recipe = Recipe.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:complete] = "You have updated user successfully."
      redirect_to user_path
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def authenticate_user
    if @current_user == nil
      redirect_to new_user_registration_path
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="">
      <h1>Welcome to <span class="glyphicon glyphicon-recipe" aria-hidden="true">Recipes!</span></h1>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="container" id="top">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>welcome to <span class="glyphicon glyphicon-recipe" aria-hidden="true">Recipes !!</span></h1>
      <p>In <span class="glyphicon glyphicon-recipe" aria-hidden="true">Recipes,</span><br>
        you can share and exchange your opinions , inpressions , and emotion<br>
        about various recipes!</p>
      <div class="btn btn-info col-xs-10 col-xs-offset-1"><%= link_to "Log in", new_user_session_path %></div>
      <div class="btn btn-success col-xs-10 col-xs-offset-1"><%= link_to "Sign up", new_user_registration_path %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RecipeSite</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navar-nav navbar-left">
        <h4>Recipes</h4>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to 'Home', user_path(current_user) %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Recipes', recipes_path %></li>
          <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', home_about_path %></li>
          <li><%= link_to 'sign up', new_user_registration_path %></li>
          <li><%= link_to 'login', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

  <% flash.each do |key, value| %>
  <%=content_tag(:div, value, class: "#{key}" ) %>
  <% end %>
  <div class="concept">
    <%= yield %>
  </div>


</body>

</html>

app/views/recipes/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= form_for(recipe, url: recipes_path, method: :post) do |f| %>
      <h1>New Recipe</h1>

      <% if recipe.errors.any? %>
      <div class="error_explanation">
        <h2><%= recipe.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field row">
        <label for="recipe_title">Title</title>
          <input class="col-xs-12 recipe_title" type="text" name="recipe[title]" id="recipe_title">
      </div>

      <div class="field row">
        <label for="recipe_opinion">Opinion</label>
        <textarea class="col-xs-12 recipe_body" name="recipe[body]" id="recipe_body"></textarea>
      </div>

      <input type="submit" name="commit" value="Create Recipe" class="btn btn-primary col-xs-12" date-disable-with="Create Recipe">
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<% if @recipe.errors.any? %>
<div class="error_explanation">
  <h2><%= @recipe.errors.count %>errors prohibited this recipe from being saved:</h2>
  <ul>
    <% @recipe.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Recipe</h1>

        <%= form_for(@recipe) do |f| %>
        <div class="field row">
          <label for="recipe_title">Title</label>
          <%= f.text_field :title, class: "col-xs-12 recipe_title" %>
        </div>
        <div class="field row">
          <label for="recipe_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12 recipe_body" %>
        </div>

        <div class="action row">
          <%= f.submit 'Update Recipe', class: "btn btn-primary col-xs-12" %>
        </div>
        <% end %>
        <%= link_to "Show", recipe_path(@recipe) %>
        |
        <%= link_to "Back", recipes_path %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'users/info', user: @user %>
      <%= render 'recipes/form', recipe: @recipe %>
    </div>

    <div class=col-xs-8>
      <h1>Recipes</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @recipes.each do |recipe| %>
          <tr>
            <td>
              <%= link_to recipe_path(recipe.user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to recipe.title, recipe_path(recipe) %></td>
            <td><%= recipe.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'users/info', user: @recipe.user %>
      <%= render 'recipes/form', recipe: @recipe_new %>
    </div>

    <div class="col-xs-8">
      <table class="table table-striped">
        <h1>Recipe detail</h1>
      </table>

      <thead>
        <tr>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@recipe.user) do %>
            <%= attachment_image_tag(@recipe.user, :profile_image, :fill, 100, 100, class: "img-circle profile-thumb", fallback: "no_image.jpg" ) %>
            <%= @recipe.user.name %>
            <% end %>
          </td>
          <td><%= link_to @recipe.title, recipe_path(@recipe) %></td>
          <td><%= @recipe.body %></td>
          <% if @recipe.user_id == current_user.id %>
          <td><span class="label label-success"><%= link_to "Edit", edit_recipe_path(@recipe) %></td></span>
          <td><span class="label label-danger"><%= link_to "Destroy", recipe_path(@recipe), method: :delete, "data-confirm" => "Are you sure?" %></td></span>
          <% end %>
        </tr>
      </tbody>
    </div>
  </div>
</div>

app/views/users/_info.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <h2>User info</h2>
      <div>
        <%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
      </div>
      <table class="table table-striped">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <%= link_to "", edit_user_path(user), class: "btn btn-default glyphicon glyphicon-wrench btn-xs btn-block" %>
    </div>

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any? %>
<div class="error_explanation">
  <h2><%= @user.errors.count %>errors prohibited this user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_for(@user) do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.attachment_field :profile_image %>

  <h4>Introduction</h4>
  <%= f.text_area :introduction %>

  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'users/info', user: @user %>
      <%= render 'recipes/form', recipe: @recipe %>
    </div>

    <div class="col-xs-8">
      <h1>Users</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"  %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <% if @user.errors.any? %>
      <div class="error_explanation">
        <h2><%= user.errors.count %>errors prohibited this user from being saved:</h2>
        <ul>
          <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <%= render 'users/info', user: @user %>
      <%= render 'recipes/form', recipe: @recipe %>

    </div>

    <div class="col-xs-8">
      <h1>Recipes</h1>
      <table class="table table-stried">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colpan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %></td>
            <td><%= link_to recipe.title, recipe_path(recipe) %></td>
            <td><%= recipe.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>